%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.7.1

-ifndef(pb_broker).
-define(pb_broker, true).

-define(pb_broker_gpb_version, "4.7.1").

-ifndef('PROTOBUFBROKER.BROKERSESSIONMESSAGE.SESSION_PB_H').
-define('PROTOBUFBROKER.BROKERSESSIONMESSAGE.SESSION_PB_H', true).
-record('ProtobufBroker.BrokerSessionMessage.Session',
        {userId = []            :: iolist() | undefined, % = 1
         expires = 0            :: integer() | undefined, % = 2, 32 bits
         token = []             :: iolist() | undefined, % = 3
         mfaToken = []          :: iolist() | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFBROKER.BROKERSESSIONMESSAGE.ANONYMOUSTRADINGSESSION_PB_H').
-define('PROTOBUFBROKER.BROKERSESSIONMESSAGE.ANONYMOUSTRADINGSESSION_PB_H', true).
-record('ProtobufBroker.BrokerSessionMessage.AnonymousTradingSession',
        {exchange = []          :: iolist() | undefined, % = 1
         token = []             :: iolist() | undefined, % = 2
         expiration = 0         :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('PROTOBUFBROKER.BROKERSESSIONMESSAGE_PB_H').
-define('PROTOBUFBROKER.BROKERSESSIONMESSAGE_PB_H', true).
-record('ProtobufBroker.BrokerSessionMessage',
        {'SessionConfig'        :: {session, pb_broker:'ProtobufBroker.BrokerSessionMessage.Session'()} | {anonymousTradingSession, pb_broker:'ProtobufBroker.BrokerSessionMessage.AnonymousTradingSession'()} | undefined, % oneof
         marketId = 0           :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('PROTOBUFBROKER.PLACEORDERREQUEST_PB_H').
-define('PROTOBUFBROKER.PLACEORDERREQUEST_PB_H', true).
-record('ProtobufBroker.PlaceOrderRequest',
        {order = undefined      :: pb_broker:'ProtobufBroker.PrivateOrder'() | undefined, % = 2
         closingOrder = undefined :: pb_broker:'ProtobufBroker.PrivateOrder'() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFBROKER.PLACEORDERRESULT_PB_H').
-define('PROTOBUFBROKER.PLACEORDERRESULT_PB_H', true).
-record('ProtobufBroker.PlaceOrderResult',
        {order = undefined      :: pb_broker:'ProtobufBroker.PrivateOrder'() | undefined, % = 2
         orderId = []           :: iolist() | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFBROKER.CANCELORDERREQUEST_PB_H').
-define('PROTOBUFBROKER.CANCELORDERREQUEST_PB_H', true).
-record('ProtobufBroker.CancelOrderRequest',
        {orderId = []           :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFBROKER.CANCELORDERRESULT_PB_H').
-define('PROTOBUFBROKER.CANCELORDERRESULT_PB_H', true).
-record('ProtobufBroker.CancelOrderResult',
        {orderId = []           :: iolist() | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFBROKER.REPLACEORDERREQUEST_PB_H').
-define('PROTOBUFBROKER.REPLACEORDERREQUEST_PB_H', true).
-record('ProtobufBroker.ReplaceOrderRequest',
        {orderId = []           :: iolist() | undefined, % = 1
         replacement = undefined :: pb_broker:'ProtobufBroker.PrivateOrder'() | undefined, % = 2
         replacementClosingOrder = undefined :: pb_broker:'ProtobufBroker.PrivateOrder'() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFBROKER.CLOSEPOSITIONREQUEST_PB_H').
-define('PROTOBUFBROKER.CLOSEPOSITIONREQUEST_PB_H', true).
-record('ProtobufBroker.ClosePositionRequest',
        {positionId = []        :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFBROKER.SYNCREQUEST_PB_H').
-define('PROTOBUFBROKER.SYNCREQUEST_PB_H', true).
-record('ProtobufBroker.SyncRequest',
        {
        }).
-endif.

-ifndef('PROTOBUFBROKER.BROKERREQUEST_PB_H').
-define('PROTOBUFBROKER.BROKERREQUEST_PB_H', true).
-record('ProtobufBroker.BrokerRequest',
        {id = []                :: iolist() | undefined, % = 1
         marketId = 0           :: integer() | undefined, % = 7, 32 bits
         'Request'              :: {placeOrderRequest, pb_broker:'ProtobufBroker.PlaceOrderRequest'()} | {cancelOrderRequest, pb_broker:'ProtobufBroker.CancelOrderRequest'()} | {replaceOrderRequest, pb_broker:'ProtobufBroker.ReplaceOrderRequest'()} | {syncRequest, pb_broker:'ProtobufBroker.SyncRequest'()} | {closePositionRequest, pb_broker:'ProtobufBroker.ClosePositionRequest'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFBROKER.ORDERSUPDATE_PB_H').
-define('PROTOBUFBROKER.ORDERSUPDATE_PB_H', true).
-record('ProtobufBroker.OrdersUpdate',
        {orders = []            :: [pb_broker:'ProtobufBroker.PrivateOrder'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFBROKER.TRADESUPDATE_PB_H').
-define('PROTOBUFBROKER.TRADESUPDATE_PB_H', true).
-record('ProtobufBroker.TradesUpdate',
        {trades = []            :: [pb_broker:'ProtobufBroker.PrivateTrade'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFBROKER.POSITIONSUPDATE_PB_H').
-define('PROTOBUFBROKER.POSITIONSUPDATE_PB_H', true).
-record('ProtobufBroker.PositionsUpdate',
        {positions = []         :: [pb_broker:'ProtobufBroker.PrivatePosition'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFBROKER.BALANCESUPDATE_PB_H').
-define('PROTOBUFBROKER.BALANCESUPDATE_PB_H', true).
-record('ProtobufBroker.BalancesUpdate',
        {balances = []          :: [pb_broker:'ProtobufBroker.Balances'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFBROKER.REQUESTRESOLUTIONUPDATE_PB_H').
-define('PROTOBUFBROKER.REQUESTRESOLUTIONUPDATE_PB_H', true).
-record('ProtobufBroker.RequestResolutionUpdate',
        {id = []                :: iolist() | undefined, % = 1
         error = 0              :: integer() | undefined, % = 2, 32 bits
         message = []           :: iolist() | undefined, % = 3
         'Result'               :: {placeOrderResult, pb_broker:'ProtobufBroker.PlaceOrderResult'()} | {cancelOrderResult, pb_broker:'ProtobufBroker.CancelOrderResult'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFBROKER.ANONYMOUSSESSIONSTATUSUPDATE_PB_H').
-define('PROTOBUFBROKER.ANONYMOUSSESSIONSTATUSUPDATE_PB_H', true).
-record('ProtobufBroker.AnonymousSessionStatusUpdate',
        {expiration = 0         :: integer() | undefined, % = 1, 32 bits
         token = []             :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFBROKER.SESSIONSTATUSUPDATE_PB_H').
-define('PROTOBUFBROKER.SESSIONSTATUSUPDATE_PB_H', true).
-record('ProtobufBroker.SessionStatusUpdate',
        {initialized = false    :: boolean() | 0 | 1 | undefined, % = 1
         syncing = false        :: boolean() | 0 | 1 | undefined, % = 2
         lastSyncTime = 0       :: integer() | undefined, % = 3, 32 bits
         syncError = 0          :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('PROTOBUFBROKER.PERMISSIONSUPDATE.AGREEMENT_PB_H').
-define('PROTOBUFBROKER.PERMISSIONSUPDATE.AGREEMENT_PB_H', true).
-record('ProtobufBroker.PermissionsUpdate.Agreement',
        {key = []               :: iolist() | undefined, % = 1
         body = []              :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFBROKER.PERMISSIONSUPDATE.LEVERAGELEVELS_PB_H').
-define('PROTOBUFBROKER.PERMISSIONSUPDATE.LEVERAGELEVELS_PB_H', true).
-record('ProtobufBroker.PermissionsUpdate.LeverageLevels',
        {buy = []               :: [iolist()] | undefined, % = 1
         sell = []              :: [iolist()] | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFBROKER.PERMISSIONSUPDATE_PB_H').
-define('PROTOBUFBROKER.PERMISSIONSUPDATE_PB_H', true).
-record('ProtobufBroker.PermissionsUpdate',
        {orderTypes = []        :: ['Market' | 'Limit' | 'StopLoss' | 'StopLossLimit' | 'TakeProfit' | 'TakeProfitLimit' | 'StopLossTakeProfit' | 'StopLossTakeProfitLimit' | 'TrailingStopLoss' | 'TrailingStopLossLimit' | 'StopLossAndLimit' | 'FillOrKill' | 'SettlePosition' | integer()] | undefined, % = 1, enum ProtobufBroker.PrivateOrder.Type
         fundingTypes = []      :: ['Spot' | 'Margin' | integer()] | undefined, % = 2, enum ProtobufBroker.FundingType
         agreements = []        :: [pb_broker:'ProtobufBroker.PermissionsUpdate.Agreement'()] | undefined, % = 4
         currencyPairAllowed = false :: boolean() | 0 | 1 | undefined, % = 5
         leverageLevels = undefined :: pb_broker:'ProtobufBroker.PermissionsUpdate.LeverageLevels'() | undefined, % = 6
         supportsOrderExpiry = false :: boolean() | 0 | 1 | undefined % = 7
        }).
-endif.

-ifndef('PROTOBUFBROKER.APIACCESSORSTATUSUPDATE_PB_H').
-define('PROTOBUFBROKER.APIACCESSORSTATUSUPDATE_PB_H', true).
-record('ProtobufBroker.APIAccessorStatusUpdate',
        {hasAccess = false      :: boolean() | 0 | 1 | undefined, % = 1
         status = 0             :: integer() | undefined, % = 2, 32 bits
         statusString = []      :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFBROKER.BROKERUPDATEMESSAGE_PB_H').
-define('PROTOBUFBROKER.BROKERUPDATEMESSAGE_PB_H', true).
-record('ProtobufBroker.BrokerUpdateMessage',
        {marketId = 0           :: integer() | undefined, % = 11, 32 bits
         'Update'               :: {ordersUpdate, pb_broker:'ProtobufBroker.OrdersUpdate'()} | {tradesUpdate, pb_broker:'ProtobufBroker.TradesUpdate'()} | {balancesUpdate, pb_broker:'ProtobufBroker.BalancesUpdate'()} | {positionsUpdate, pb_broker:'ProtobufBroker.PositionsUpdate'()} | {requestResolutionUpdate, pb_broker:'ProtobufBroker.RequestResolutionUpdate'()} | {anonymousSessionStatusUpdate, pb_broker:'ProtobufBroker.AnonymousSessionStatusUpdate'()} | {permissionsUpdate, pb_broker:'ProtobufBroker.PermissionsUpdate'()} | {sessionStatusUpdate, pb_broker:'ProtobufBroker.SessionStatusUpdate'()} | {apiAccessorStatusUpdate, pb_broker:'ProtobufBroker.APIAccessorStatusUpdate'()} | {authenticationResult, pb_broker:'ProtobufStream.AuthenticationResult'()} | {subscriptionResult, pb_broker:'ProtobufStream.SubscriptionResult'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATEORDER.PRICEPARAM_PB_H').
-define('PROTOBUFBROKER.PRIVATEORDER.PRICEPARAM_PB_H', true).
-record('ProtobufBroker.PrivateOrder.PriceParam',
        {value = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         valueString = []       :: iolist() | undefined, % = 3
         type = 'AbsoluteValue' :: 'AbsoluteValue' | 'OffsetValue' | 'PrecentageOffsetValue' | integer() | undefined % = 2, enum ProtobufBroker.PrivateOrder.PriceParamType
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATEORDER_PB_H').
-define('PROTOBUFBROKER.PRIVATEORDER_PB_H', true).
-record('ProtobufBroker.PrivateOrder',
        {id = []                :: iolist() | undefined, % = 1
         time = 0               :: integer() | undefined, % = 2, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         side = 0               :: integer() | undefined, % = 5, 32 bits
         type = 'Market'        :: 'Market' | 'Limit' | 'StopLoss' | 'StopLossLimit' | 'TakeProfit' | 'TakeProfitLimit' | 'StopLossTakeProfit' | 'StopLossTakeProfitLimit' | 'TrailingStopLoss' | 'TrailingStopLossLimit' | 'StopLossAndLimit' | 'FillOrKill' | 'SettlePosition' | integer() | undefined, % = 6, enum ProtobufBroker.PrivateOrder.Type
         fundingType = 'Spot'   :: 'Spot' | 'Margin' | integer() | undefined, % = 7, enum ProtobufBroker.FundingType
         priceParams = []       :: [pb_broker:'ProtobufBroker.PrivateOrder.PriceParam'()] | undefined, % = 8
         amountParam = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 9
         amountParamString = [] :: iolist() | undefined, % = 16
         amountFilledString = [] :: iolist() | undefined, % = 17
         leverage = []          :: iolist() | undefined, % = 10
         currentStop = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 11
         initialStop = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 12
         currentStopString = [] :: iolist() | undefined, % = 18
         initialStopString = [] :: iolist() | undefined, % = 19
         startTime = 0          :: integer() | undefined, % = 13, 32 bits
         expireTime = 0         :: integer() | undefined, % = 14, 32 bits
         rate = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 15
         hasClosingOrder = false :: boolean() | 0 | 1 | undefined, % = 20
         closingOrderType = 'Market' :: 'Market' | 'Limit' | 'StopLoss' | 'StopLossLimit' | 'TakeProfit' | 'TakeProfitLimit' | 'StopLossTakeProfit' | 'StopLossTakeProfitLimit' | 'TrailingStopLoss' | 'TrailingStopLossLimit' | 'StopLossAndLimit' | 'FillOrKill' | 'SettlePosition' | integer() | undefined, % = 21, enum ProtobufBroker.PrivateOrder.Type
         closingOrderPriceParams = [] :: [pb_broker:'ProtobufBroker.PrivateOrder.PriceParam'()] | undefined % = 22
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATETRADE_PB_H').
-define('PROTOBUFBROKER.PRIVATETRADE_PB_H', true).
-record('ProtobufBroker.PrivateTrade',
        {externalId = []        :: iolist() | undefined, % = 7
         orderId = []           :: iolist() | undefined, % = 8
         time = 0               :: integer() | undefined, % = 2, 32 bits
         timeMillis = 0         :: integer() | undefined, % = 6, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         priceString = []       :: iolist() | undefined, % = 9
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         amountString = []      :: iolist() | undefined, % = 10
         side = 0               :: integer() | undefined, % = 5, 32 bits
         id = 0                 :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATEPOSITION_PB_H').
-define('PROTOBUFBROKER.PRIVATEPOSITION_PB_H', true).
-record('ProtobufBroker.PrivatePosition',
        {id = []                :: iolist() | undefined, % = 1
         time = 0               :: integer() | undefined, % = 2, 32 bits
         side = 0               :: integer() | undefined, % = 3, 32 bits
         avgPrice = 0.0         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         avgPriceString = []    :: iolist() | undefined, % = 9
         amountOpen = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5
         amountClosed = 0.0     :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         amountOpenString = []  :: iolist() | undefined, % = 10
         amountClosedString = [] :: iolist() | undefined, % = 11
         orderIds = []          :: [iolist()] | undefined, % = 7
         tradeIds = []          :: [iolist()] | undefined % = 8
        }).
-endif.

-ifndef('PROTOBUFBROKER.BALANCE_PB_H').
-define('PROTOBUFBROKER.BALANCE_PB_H', true).
-record('ProtobufBroker.Balance',
        {currency = []          :: iolist() | undefined, % = 1
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         amountString = []      :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFBROKER.BALANCES_PB_H').
-define('PROTOBUFBROKER.BALANCES_PB_H', true).
-record('ProtobufBroker.Balances',
        {fundingType = 'Spot'   :: 'Spot' | 'Margin' | integer() | undefined, % = 1, enum ProtobufBroker.FundingType
         balances = []          :: [pb_broker:'ProtobufBroker.Balance'()] | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFSTREAM.STREAMMESSAGE_PB_H').
-define('PROTOBUFSTREAM.STREAMMESSAGE_PB_H', true).
-record('ProtobufStream.StreamMessage',
        {body                   :: {authenticationResult, pb_broker:'ProtobufStream.AuthenticationResult'()} | {subscriptionResult, pb_broker:'ProtobufStream.SubscriptionResult'()} | {unsubscriptionResult, pb_broker:'ProtobufStream.UnsubscriptionResult'()} | {missedMessages, pb_broker:'ProtobufStream.MissedMessages'()} | {marketUpdate, pb_broker:'ProtobufMarkets.MarketUpdateMessage'()} | {pairUpdate, pb_broker:'ProtobufMarkets.PairUpdateMessage'()} | {assetUpdate, pb_broker:'ProtobufMarkets.AssetUpdateMessage'()} | {indexUpdate, pb_broker:'ProtobufMarkets.IndexUpdateMessage'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFSTREAM.AUTHENTICATIONRESULT_PB_H').
-define('PROTOBUFSTREAM.AUTHENTICATIONRESULT_PB_H', true).
-record('ProtobufStream.AuthenticationResult',
        {status = 'UNKNOWN'     :: 'UNKNOWN' | 'AUTHENTICATED' | 'BAD_NONCE' | 'BAD_TOKEN' | 'TOKEN_EXPIRED' | integer() | undefined % = 1, enum ProtobufStream.AuthenticationResult.Status
        }).
-endif.

-ifndef('PROTOBUFSTREAM.SUBSCRIPTIONRESULT_PB_H').
-define('PROTOBUFSTREAM.SUBSCRIPTIONRESULT_PB_H', true).
-record('ProtobufStream.SubscriptionResult',
        {subscribed = []        :: [iolist()] | undefined, % = 1
         failed = []            :: [pb_broker:'ProtobufStream.SubscribeError'()] | undefined, % = 2
         status = undefined     :: pb_broker:'ProtobufStream.SubscriptionStatus'() | undefined, % = 3
         subscriptions = []     :: [pb_broker:'ProtobufClient.ClientSubscription'()] | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFSTREAM.UNSUBSCRIPTIONRESULT_PB_H').
-define('PROTOBUFSTREAM.UNSUBSCRIPTIONRESULT_PB_H', true).
-record('ProtobufStream.UnsubscriptionResult',
        {unsubscribed = []      :: [iolist()] | undefined, % = 1
         failed = []            :: [pb_broker:'ProtobufStream.UnsubscribeError'()] | undefined, % = 2
         status = undefined     :: pb_broker:'ProtobufStream.SubscriptionStatus'() | undefined, % = 3
         subscriptions = []     :: [pb_broker:'ProtobufClient.ClientSubscription'()] | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFSTREAM.SUBSCRIBEERROR_PB_H').
-define('PROTOBUFSTREAM.SUBSCRIBEERROR_PB_H', true).
-record('ProtobufStream.SubscribeError',
        {key = []               :: iolist() | undefined, % = 1
         error = []             :: iolist() | undefined, % = 2
         subscription = undefined :: pb_broker:'ProtobufClient.ClientSubscription'() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFSTREAM.UNSUBSCRIBEERROR_PB_H').
-define('PROTOBUFSTREAM.UNSUBSCRIBEERROR_PB_H', true).
-record('ProtobufStream.UnsubscribeError',
        {key = []               :: iolist() | undefined, % = 1
         error = []             :: iolist() | undefined, % = 2
         subscription = undefined :: pb_broker:'ProtobufClient.ClientSubscription'() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFSTREAM.SUBSCRIPTIONSTATUS_PB_H').
-define('PROTOBUFSTREAM.SUBSCRIPTIONSTATUS_PB_H', true).
-record('ProtobufStream.SubscriptionStatus',
        {keys = []              :: [iolist()] | undefined, % = 1
         subscriptions = []     :: [pb_broker:'ProtobufClient.ClientSubscription'()] | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFSTREAM.MISSEDMESSAGES_PB_H').
-define('PROTOBUFSTREAM.MISSEDMESSAGES_PB_H', true).
-record('ProtobufStream.MissedMessages',
        {numMissedMessages = 0  :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTMESSAGE_PB_H').
-define('PROTOBUFCLIENT.CLIENTMESSAGE_PB_H', true).
-record('ProtobufClient.ClientMessage',
        {body                   :: {identification, pb_broker:'ProtobufClient.ClientIdentificationMessage'()} | {subscribe, pb_broker:'ProtobufClient.ClientSubscribeMessage'()} | {unsubscribe, pb_broker:'ProtobufClient.ClientUnsubscribeMessage'()} | {webAuthentication, pb_broker:'ProtobufClient.WebAuthenticationMessage'()} | {apiAuthentication, pb_broker:'ProtobufClient.APIAuthenticationMessage'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTIDENTIFICATIONMESSAGE_PB_H').
-define('PROTOBUFCLIENT.CLIENTIDENTIFICATIONMESSAGE_PB_H', true).
-record('ProtobufClient.ClientIdentificationMessage',
        {useragent = []         :: iolist() | undefined, % = 1
         revision = []          :: iolist() | undefined, % = 2
         integration = []       :: iolist() | undefined, % = 3
         locale = []            :: iolist() | undefined, % = 4
         subscriptions = []     :: [iolist()] | undefined % = 5
        }).
-endif.

-ifndef('PROTOBUFCLIENT.WEBAUTHENTICATIONMESSAGE_PB_H').
-define('PROTOBUFCLIENT.WEBAUTHENTICATIONMESSAGE_PB_H', true).
-record('ProtobufClient.WebAuthenticationMessage',
        {identification = undefined :: pb_broker:'ProtobufClient.ClientIdentificationMessage'() | undefined, % = 1
         token = []             :: iolist() | undefined, % = 2
         nonce = []             :: iolist() | undefined, % = 3
         access_list = []       :: [iolist()] | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFCLIENT.TRADESESSIONAUTH_PB_H').
-define('PROTOBUFCLIENT.TRADESESSIONAUTH_PB_H', true).
-record('ProtobufClient.TradeSessionAuth',
        {api_key = []           :: iolist() | undefined, % = 1
         api_secret = []        :: iolist() | undefined, % = 2
         customer_id = []       :: iolist() | undefined, % = 3
         key_passphrase = []    :: iolist() | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFCLIENT.TRADESUBSCRIPTION_PB_H').
-define('PROTOBUFCLIENT.TRADESUBSCRIPTION_PB_H', true).
-record('ProtobufClient.TradeSubscription',
        {marketId = []          :: iolist() | undefined, % = 1
         auth = undefined       :: pb_broker:'ProtobufClient.TradeSessionAuth'() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFCLIENT.STREAMSUBSCRIPTION_PB_H').
-define('PROTOBUFCLIENT.STREAMSUBSCRIPTION_PB_H', true).
-record('ProtobufClient.StreamSubscription',
        {resource = []          :: iolist() | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTSUBSCRIPTION_PB_H').
-define('PROTOBUFCLIENT.CLIENTSUBSCRIPTION_PB_H', true).
-record('ProtobufClient.ClientSubscription',
        {body                   :: {stream_subscription, pb_broker:'ProtobufClient.StreamSubscription'()} | {trade_subscription, pb_broker:'ProtobufClient.TradeSubscription'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFCLIENT.APIAUTHENTICATIONMESSAGE_PB_H').
-define('PROTOBUFCLIENT.APIAUTHENTICATIONMESSAGE_PB_H', true).
-record('ProtobufClient.APIAuthenticationMessage',
        {token = []             :: iolist() | undefined, % = 1
         nonce = []             :: iolist() | undefined, % = 2
         api_key = []           :: iolist() | undefined, % = 3
         source = 'UNKNOWN'     :: 'UNKNOWN' | 'GOLANG_SDK' | 'JAVASCRIPT_SDK' | 'NODE_SDK' | 'RUST_SDK' | 'CW_WEB' | integer() | undefined, % = 4, enum ProtobufClient.APIAuthenticationMessage.Source
         version = []           :: iolist() | undefined, % = 5
         subscriptions = []     :: [iolist()] | undefined, % = 6
         client_subscriptions = [] :: [pb_broker:'ProtobufClient.ClientSubscription'()] | undefined % = 7
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTSESSIONMESSAGE.SESSION_PB_H').
-define('PROTOBUFCLIENT.CLIENTSESSIONMESSAGE.SESSION_PB_H', true).
-record('ProtobufClient.ClientSessionMessage.Session',
        {userId = []            :: iolist() | undefined, % = 1
         expires = 0            :: integer() | undefined, % = 2, 32 bits
         token = []             :: iolist() | undefined, % = 3
         mfaToken = []          :: iolist() | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTSESSIONMESSAGE.ANONYMOUSTRADINGSESSION_PB_H').
-define('PROTOBUFCLIENT.CLIENTSESSIONMESSAGE.ANONYMOUSTRADINGSESSION_PB_H', true).
-record('ProtobufClient.ClientSessionMessage.AnonymousTradingSession',
        {exchange = []          :: iolist() | undefined, % = 1
         token = []             :: iolist() | undefined, % = 2
         expiration = 0         :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTSESSIONMESSAGE_PB_H').
-define('PROTOBUFCLIENT.CLIENTSESSIONMESSAGE_PB_H', true).
-record('ProtobufClient.ClientSessionMessage',
        {'SessionConfig'        :: {session, pb_broker:'ProtobufClient.ClientSessionMessage.Session'()} | {anonymousTradingSession, pb_broker:'ProtobufClient.ClientSessionMessage.AnonymousTradingSession'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTSUBSCRIBEMESSAGE_PB_H').
-define('PROTOBUFCLIENT.CLIENTSUBSCRIBEMESSAGE_PB_H', true).
-record('ProtobufClient.ClientSubscribeMessage',
        {subscriptionKeys = []  :: [iolist()] | undefined, % = 1
         subscriptions = []     :: [pb_broker:'ProtobufClient.ClientSubscription'()] | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFCLIENT.CLIENTUNSUBSCRIBEMESSAGE_PB_H').
-define('PROTOBUFCLIENT.CLIENTUNSUBSCRIBEMESSAGE_PB_H', true).
-record('ProtobufClient.ClientUnsubscribeMessage',
        {subscriptionKeys = []  :: [iolist()] | undefined, % = 1
         subscriptions = []     :: [pb_broker:'ProtobufClient.ClientSubscription'()] | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFMARKETS.MARKET_PB_H').
-define('PROTOBUFMARKETS.MARKET_PB_H', true).
-record('ProtobufMarkets.Market',
        {exchangeId = 0         :: non_neg_integer() | undefined, % = 3, 32 bits
         currencyPairId = 0     :: non_neg_integer() | undefined, % = 4, 32 bits
         marketId = 0           :: non_neg_integer() | undefined, % = 5, 32 bits
         exchange = []          :: iolist() | undefined, % = 1
         currencyPair = []      :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ORDER_PB_H').
-define('PROTOBUFMARKETS.ORDER_PB_H', true).
-record('ProtobufMarkets.Order',
        {priceStr = []          :: iolist() | undefined, % = 3
         amountStr = []         :: iolist() | undefined, % = 4
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFMARKETS.TRADE_PB_H').
-define('PROTOBUFMARKETS.TRADE_PB_H', true).
-record('ProtobufMarkets.Trade',
        {externalId = []        :: iolist() | undefined, % = 11
         timestamp = 0          :: integer() | undefined, % = 2, 32 bits
         timestampMillis = 0    :: integer() | undefined, % = 5, 32 bits
         timestampNano = 0      :: integer() | undefined, % = 10, 32 bits
         priceStr = []          :: iolist() | undefined, % = 8
         amountStr = []         :: iolist() | undefined, % = 9
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         priceDouble = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         amountDouble = 0.0     :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 7
         id = 0                 :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PROTOBUFMARKETS.MARKETUPDATEMESSAGE_PB_H').
-define('PROTOBUFMARKETS.MARKETUPDATEMESSAGE_PB_H', true).
-record('ProtobufMarkets.MarketUpdateMessage',
        {market = undefined     :: pb_broker:'ProtobufMarkets.Market'() | undefined, % = 9
         'Update'               :: {orderBookUpdate, pb_broker:'ProtobufMarkets.OrderBookUpdate'()} | {orderBookDeltaUpdate, pb_broker:'ProtobufMarkets.OrderBookDeltaUpdate'()} | {orderBookSpreadUpdate, pb_broker:'ProtobufMarkets.OrderBookSpreadUpdate'()} | {tradesUpdate, pb_broker:'ProtobufMarkets.TradesUpdate'()} | {intervalsUpdate, pb_broker:'ProtobufMarkets.IntervalsUpdate'()} | {summaryUpdate, pb_broker:'ProtobufMarkets.SummaryUpdate'()} | {sparklineUpdate, pb_broker:'ProtobufMarkets.SparklineUpdate'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ORDERBOOKUPDATE_PB_H').
-define('PROTOBUFMARKETS.ORDERBOOKUPDATE_PB_H', true).
-record('ProtobufMarkets.OrderBookUpdate',
        {aggregationModulusStr = [] :: iolist() | undefined, % = 4
         seqNum = 0             :: integer() | undefined, % = 5, 32 bits
         bids = []              :: [pb_broker:'ProtobufMarkets.Order'()] | undefined, % = 1
         asks = []              :: [pb_broker:'ProtobufMarkets.Order'()] | undefined, % = 2
         aggregationModulus = 0.0 :: float() | integer() | infinity | '-infinity' | nan | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ORDERBOOKDELTAUPDATE.ORDERDELTAS_PB_H').
-define('PROTOBUFMARKETS.ORDERBOOKDELTAUPDATE.ORDERDELTAS_PB_H', true).
-record('ProtobufMarkets.OrderBookDeltaUpdate.OrderDeltas',
        {set = []               :: [pb_broker:'ProtobufMarkets.Order'()] | undefined, % = 1
         delta = []             :: [pb_broker:'ProtobufMarkets.Order'()] | undefined, % = 2
         remove = []            :: [float() | integer() | infinity | '-infinity' | nan] | undefined, % = 3
         removeStr = []         :: [iolist()] | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ORDERBOOKDELTAUPDATE_PB_H').
-define('PROTOBUFMARKETS.ORDERBOOKDELTAUPDATE_PB_H', true).
-record('ProtobufMarkets.OrderBookDeltaUpdate',
        {aggregationModulus = 0.0 :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         aggregationModulusStr = [] :: iolist() | undefined, % = 4
         seqNum = 0             :: integer() | undefined, % = 5, 32 bits
         bids = undefined       :: pb_broker:'ProtobufMarkets.OrderBookDeltaUpdate.OrderDeltas'() | undefined, % = 1
         asks = undefined       :: pb_broker:'ProtobufMarkets.OrderBookDeltaUpdate.OrderDeltas'() | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ORDERBOOKSPREADUPDATE_PB_H').
-define('PROTOBUFMARKETS.ORDERBOOKSPREADUPDATE_PB_H', true).
-record('ProtobufMarkets.OrderBookSpreadUpdate',
        {timestamp = 0          :: integer() | undefined, % = 1, 32 bits
         bid = undefined        :: pb_broker:'ProtobufMarkets.Order'() | undefined, % = 2
         ask = undefined        :: pb_broker:'ProtobufMarkets.Order'() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFMARKETS.TRADESUPDATE_PB_H').
-define('PROTOBUFMARKETS.TRADESUPDATE_PB_H', true).
-record('ProtobufMarkets.TradesUpdate',
        {trades = []            :: [pb_broker:'ProtobufMarkets.Trade'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFMARKETS.INTERVAL.OHLC_PB_H').
-define('PROTOBUFMARKETS.INTERVAL.OHLC_PB_H', true).
-record('ProtobufMarkets.Interval.OHLC',
        {openStr = []           :: iolist() | undefined, % = 5
         highStr = []           :: iolist() | undefined, % = 6
         lowStr = []            :: iolist() | undefined, % = 7
         closeStr = []          :: iolist() | undefined, % = 8
         open = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         high = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         low = 0.0              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         close = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFMARKETS.INTERVAL_PB_H').
-define('PROTOBUFMARKETS.INTERVAL_PB_H', true).
-record('ProtobufMarkets.Interval',
        {closetime = 0          :: integer() | undefined, % = 1, 32 bits
         period = 0             :: integer() | undefined, % = 4, 32 bits
         ohlc = undefined       :: pb_broker:'ProtobufMarkets.Interval.OHLC'() | undefined, % = 2
         volumeBaseStr = []     :: iolist() | undefined, % = 6
         volumeQuoteStr = []    :: iolist() | undefined, % = 7
         volumeBase = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         volumeQuote = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined % = 5
        }).
-endif.

-ifndef('PROTOBUFMARKETS.INTERVALSUPDATE_PB_H').
-define('PROTOBUFMARKETS.INTERVALSUPDATE_PB_H', true).
-record('ProtobufMarkets.IntervalsUpdate',
        {intervals = []         :: [pb_broker:'ProtobufMarkets.Interval'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFMARKETS.SUMMARYUPDATE_PB_H').
-define('PROTOBUFMARKETS.SUMMARYUPDATE_PB_H', true).
-record('ProtobufMarkets.SummaryUpdate',
        {lastStr = []           :: iolist() | undefined, % = 10
         highStr = []           :: iolist() | undefined, % = 11
         lowStr = []            :: iolist() | undefined, % = 12
         volumeBaseStr = []     :: iolist() | undefined, % = 13
         volumeQuoteStr = []    :: iolist() | undefined, % = 14
         changeAbsoluteStr = [] :: iolist() | undefined, % = 15
         changePercentStr = []  :: iolist() | undefined, % = 16
         numTrades = 0          :: integer() | undefined, % = 8, 32 bits
         last = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         high = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         low = 0.0              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         volumeBase = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5
         volumeQuote = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 9
         changeAbsolute = 0.0   :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         changePercent = 0.0    :: float() | integer() | infinity | '-infinity' | nan | undefined % = 7
        }).
-endif.

-ifndef('PROTOBUFMARKETS.SPARKLINEUPDATE_PB_H').
-define('PROTOBUFMARKETS.SPARKLINEUPDATE_PB_H', true).
-record('ProtobufMarkets.SparklineUpdate',
        {time = 0               :: integer() | undefined, % = 2, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         priceStr = []          :: iolist() | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFMARKETS.INDEX_PB_H').
-define('PROTOBUFMARKETS.INDEX_PB_H', true).
-record('ProtobufMarkets.Index',
        {id = 0                 :: non_neg_integer() | undefined, % = 1, 32 bits
         symbol = []            :: iolist() | undefined, % = 2
         indexType = []         :: iolist() | undefined, % = 3
         cwIndex = false        :: boolean() | 0 | 1 | undefined, % = 4
         exchangeId = 0         :: non_neg_integer() | undefined, % = 5, 32 bits
         instrumentId = 0       :: non_neg_integer() | undefined % = 6, 32 bits
        }).
-endif.

-ifndef('PROTOBUFMARKETS.INDEXUPDATEMESSAGE_PB_H').
-define('PROTOBUFMARKETS.INDEXUPDATEMESSAGE_PB_H', true).
-record('ProtobufMarkets.IndexUpdateMessage',
        {index = undefined      :: pb_broker:'ProtobufMarkets.Index'() | undefined, % = 1
         'Update'               :: {tickerUpdate, pb_broker:'ProtobufMarkets.TickerUpdate'()} | {intervalsUpdate, pb_broker:'ProtobufMarkets.IntervalsUpdate'()} | {summaryUpdate, pb_broker:'ProtobufMarkets.SummaryUpdate'()} | {sparklineUpdate, pb_broker:'ProtobufMarkets.SparklineUpdate'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFMARKETS.TICKERUPDATE_PB_H').
-define('PROTOBUFMARKETS.TICKERUPDATE_PB_H', true).
-record('ProtobufMarkets.TickerUpdate',
        {tickers = []           :: [pb_broker:'ProtobufMarkets.Ticker'()] | undefined % = 1
        }).
-endif.

-ifndef('PROTOBUFMARKETS.TICKER_PB_H').
-define('PROTOBUFMARKETS.TICKER_PB_H', true).
-record('ProtobufMarkets.Ticker',
        {value = []             :: iolist() | undefined, % = 1
         timestamp = 0          :: integer() | undefined, % = 2, 32 bits
         timestampNano = 0      :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRUPDATEMESSAGE_PB_H').
-define('PROTOBUFMARKETS.PAIRUPDATEMESSAGE_PB_H', true).
-record('ProtobufMarkets.PairUpdateMessage',
        {pair = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         'Update'               :: {vwapUpdate, pb_broker:'ProtobufMarkets.PairVwapUpdate'()} | {performanceUpdate, pb_broker:'ProtobufMarkets.PairPerformanceUpdate'()} | {trendlineUpdate, pb_broker:'ProtobufMarkets.PairTrendlineUpdate'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRVWAPUPDATE_PB_H').
-define('PROTOBUFMARKETS.PAIRVWAPUPDATE_PB_H', true).
-record('ProtobufMarkets.PairVwapUpdate',
        {vwap = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         timestamp = 0          :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRPERFORMANCEUPDATE_PB_H').
-define('PROTOBUFMARKETS.PAIRPERFORMANCEUPDATE_PB_H', true).
-record('ProtobufMarkets.PairPerformanceUpdate',
        {window = []            :: iolist() | undefined, % = 1
         performance = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRTRENDLINEUPDATE_PB_H').
-define('PROTOBUFMARKETS.PAIRTRENDLINEUPDATE_PB_H', true).
-record('ProtobufMarkets.PairTrendlineUpdate',
        {window = []            :: iolist() | undefined, % = 1
         time = 0               :: integer() | undefined, % = 2, 32 bits
         price = []             :: iolist() | undefined, % = 3
         volume = []            :: iolist() | undefined % = 4
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ASSETUPDATEMESSAGE_PB_H').
-define('PROTOBUFMARKETS.ASSETUPDATEMESSAGE_PB_H', true).
-record('ProtobufMarkets.AssetUpdateMessage',
        {asset = 0              :: integer() | undefined, % = 1, 32 bits
         'Update'               :: {usdVolumeUpdate, pb_broker:'ProtobufMarkets.AssetUSDVolumeUpdate'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFMARKETS.ASSETUSDVOLUMEUPDATE_PB_H').
-define('PROTOBUFMARKETS.ASSETUSDVOLUMEUPDATE_PB_H', true).
-record('ProtobufMarkets.AssetUSDVolumeUpdate',
        {volume = []            :: iolist() | undefined % = 1
        }).
-endif.

-endif.
