%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.7.1

-ifndef(pb_pair).
-define(pb_pair, true).

-define(pb_pair_gpb_version, "4.7.1").

-ifndef('PROTOBUFMARKETS.PAIRUPDATEMESSAGE_PB_H').
-define('PROTOBUFMARKETS.PAIRUPDATEMESSAGE_PB_H', true).
-record('ProtobufMarkets.PairUpdateMessage',
        {pair = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         'Update'               :: {vwapUpdate, pb_pair:'ProtobufMarkets.PairVwapUpdate'()} | {performanceUpdate, pb_pair:'ProtobufMarkets.PairPerformanceUpdate'()} | {trendlineUpdate, pb_pair:'ProtobufMarkets.PairTrendlineUpdate'()} | undefined % oneof
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRVWAPUPDATE_PB_H').
-define('PROTOBUFMARKETS.PAIRVWAPUPDATE_PB_H', true).
-record('ProtobufMarkets.PairVwapUpdate',
        {vwap = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         timestamp = 0          :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRPERFORMANCEUPDATE_PB_H').
-define('PROTOBUFMARKETS.PAIRPERFORMANCEUPDATE_PB_H', true).
-record('ProtobufMarkets.PairPerformanceUpdate',
        {window = []            :: iolist() | undefined, % = 1
         performance = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
        }).
-endif.

-ifndef('PROTOBUFMARKETS.PAIRTRENDLINEUPDATE_PB_H').
-define('PROTOBUFMARKETS.PAIRTRENDLINEUPDATE_PB_H', true).
-record('ProtobufMarkets.PairTrendlineUpdate',
        {window = []            :: iolist() | undefined, % = 1
         time = 0               :: integer() | undefined, % = 2, 32 bits
         price = []             :: iolist() | undefined, % = 3
         volume = []            :: iolist() | undefined % = 4
        }).
-endif.

-endif.
