%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.7.1

-ifndef(pb_private).
-define(pb_private, true).

-define(pb_private_gpb_version, "4.7.1").

-ifndef('PROTOBUFBROKER.PRIVATEORDER.PRICEPARAM_PB_H').
-define('PROTOBUFBROKER.PRIVATEORDER.PRICEPARAM_PB_H', true).
-record('ProtobufBroker.PrivateOrder.PriceParam',
        {value = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         valueString = []       :: iolist() | undefined, % = 3
         type = 'AbsoluteValue' :: 'AbsoluteValue' | 'OffsetValue' | 'PrecentageOffsetValue' | integer() | undefined % = 2, enum ProtobufBroker.PrivateOrder.PriceParamType
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATEORDER_PB_H').
-define('PROTOBUFBROKER.PRIVATEORDER_PB_H', true).
-record('ProtobufBroker.PrivateOrder',
        {id = []                :: iolist() | undefined, % = 1
         time = 0               :: integer() | undefined, % = 2, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         side = 0               :: integer() | undefined, % = 5, 32 bits
         type = 'Market'        :: 'Market' | 'Limit' | 'StopLoss' | 'StopLossLimit' | 'TakeProfit' | 'TakeProfitLimit' | 'StopLossTakeProfit' | 'StopLossTakeProfitLimit' | 'TrailingStopLoss' | 'TrailingStopLossLimit' | 'StopLossAndLimit' | 'FillOrKill' | 'SettlePosition' | integer() | undefined, % = 6, enum ProtobufBroker.PrivateOrder.Type
         fundingType = 'Spot'   :: 'Spot' | 'Margin' | integer() | undefined, % = 7, enum ProtobufBroker.FundingType
         priceParams = []       :: [pb_private:'ProtobufBroker.PrivateOrder.PriceParam'()] | undefined, % = 8
         amountParam = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 9
         amountParamString = [] :: iolist() | undefined, % = 16
         amountFilledString = [] :: iolist() | undefined, % = 17
         leverage = []          :: iolist() | undefined, % = 10
         currentStop = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 11
         initialStop = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 12
         currentStopString = [] :: iolist() | undefined, % = 18
         initialStopString = [] :: iolist() | undefined, % = 19
         startTime = 0          :: integer() | undefined, % = 13, 32 bits
         expireTime = 0         :: integer() | undefined, % = 14, 32 bits
         rate = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 15
         hasClosingOrder = false :: boolean() | 0 | 1 | undefined, % = 20
         closingOrderType = 'Market' :: 'Market' | 'Limit' | 'StopLoss' | 'StopLossLimit' | 'TakeProfit' | 'TakeProfitLimit' | 'StopLossTakeProfit' | 'StopLossTakeProfitLimit' | 'TrailingStopLoss' | 'TrailingStopLossLimit' | 'StopLossAndLimit' | 'FillOrKill' | 'SettlePosition' | integer() | undefined, % = 21, enum ProtobufBroker.PrivateOrder.Type
         closingOrderPriceParams = [] :: [pb_private:'ProtobufBroker.PrivateOrder.PriceParam'()] | undefined % = 22
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATETRADE_PB_H').
-define('PROTOBUFBROKER.PRIVATETRADE_PB_H', true).
-record('ProtobufBroker.PrivateTrade',
        {externalId = []        :: iolist() | undefined, % = 7
         orderId = []           :: iolist() | undefined, % = 8
         time = 0               :: integer() | undefined, % = 2, 32 bits
         timeMillis = 0         :: integer() | undefined, % = 6, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         priceString = []       :: iolist() | undefined, % = 9
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         amountString = []      :: iolist() | undefined, % = 10
         side = 0               :: integer() | undefined, % = 5, 32 bits
         id = 0                 :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PROTOBUFBROKER.PRIVATEPOSITION_PB_H').
-define('PROTOBUFBROKER.PRIVATEPOSITION_PB_H', true).
-record('ProtobufBroker.PrivatePosition',
        {id = []                :: iolist() | undefined, % = 1
         time = 0               :: integer() | undefined, % = 2, 32 bits
         side = 0               :: integer() | undefined, % = 3, 32 bits
         avgPrice = 0.0         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         avgPriceString = []    :: iolist() | undefined, % = 9
         amountOpen = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5
         amountClosed = 0.0     :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         amountOpenString = []  :: iolist() | undefined, % = 10
         amountClosedString = [] :: iolist() | undefined, % = 11
         orderIds = []          :: [iolist()] | undefined, % = 7
         tradeIds = []          :: [iolist()] | undefined % = 8
        }).
-endif.

-ifndef('PROTOBUFBROKER.BALANCE_PB_H').
-define('PROTOBUFBROKER.BALANCE_PB_H', true).
-record('ProtobufBroker.Balance',
        {currency = []          :: iolist() | undefined, % = 1
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         amountString = []      :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('PROTOBUFBROKER.BALANCES_PB_H').
-define('PROTOBUFBROKER.BALANCES_PB_H', true).
-record('ProtobufBroker.Balances',
        {fundingType = 'Spot'   :: 'Spot' | 'Margin' | integer() | undefined, % = 1, enum ProtobufBroker.FundingType
         balances = []          :: [pb_private:'ProtobufBroker.Balance'()] | undefined % = 2
        }).
-endif.

-endif.
